### ISSUE TITLE
independent zooming of x and y axes

### ISSUE THREAD

**Issue by parosen** [aivazis/qed#1]
For certain images, it is convenient to display them with a different zoom factor in x and y. This can be to "square-up" the image so it looks more like 1:1 aspect ratio you would see with your eyes, or to scale one image to match another with a different aspect ratio.  If qed could have the ability to independently zoom in x and y that would be great.

**Comment by parosen** [comment]
Great new capability.  Can you make the odd intervals clickable so that it is possible to guarantee log integer zooming, as was originally conceived?

**Comment by aivazis** [comment]
Addressed in 0fe7063f99213556d3f9e450dfa530eb6ee6e7ce. The major and minor tick marks are now clickable, so selecting the odd integer zoom levels can be now be accomplished by clicking on any minor tick mark
