### ISSUE TITLE
Update QED S3 configuration panel to allow special characters like dashes in Profile field

### ISSUE THREAD

**Issue by jeffreypon** [aivazis/qed#38]
Update QED S3 configuration panel to allow special characters like dashes in Profile field. On-demand users would use aws-login script and use a "saml-pub" profile. However, special characters like dash is not allowed in the profile field so on-demand users can't populate that field. Update profile field to allow dashes.
![image](https://github.com/aivazis/qed/assets/28875376/3c8c0f10-ad9f-4d08-b284-4de2ef829cc5)

**Comment by aivazis** [comment]
Fixed in 965c0413ab2f7865b10ab00c90d29347b75f43ad
