### ISSUE TITLE
Update h5library in QED to allow temp credential's token

### ISSUE THREAD

**Issue by jeffreypon** [aivazis/qed#39]
If users have to acquire a temp credential token, the current h5library doesn't support temp credential token. Mike submitted a PR request to update the h5library to support this to the hdf group. 

QED as it relies on that library so QED currently doesn't support temp credential token because the h5library doesn't support it. When the updated h5library support for temp credential token is available, it needs to be pulled into QED.

**Comment by aivazis** [comment]
The upcoming release of `hdf5` will include support for all this, so this is no longer a `qed` issue.
