### ISSUE TITLE
Draggable path

### ISSUE THREAD

**Issue by parosen** [aivazis/qed#45]
Opening this as an issue, but really just an idea to think about.

Being able to click and hold on a line segment on the path and drag the entire connected path to a new location would facilitate centering a region on an image feature.  Would be useful for multiple similarly shaped region statistics computation.

**Comment by aivazis** [comment]
if i understand correctly what you are asking for, this is already supported: select a point by clicking on it, select any point after it by shift+click, which let's select multiple nodes. you can then drag all selected segments as a group. similar behavior is supported on the node table in the measure control: click a node, then shift+click on any node below it to do the multimode selection. you can then drag the selected portion of the path.

let me know if this covers what you had in mind.

**Comment by parosen** [comment]
Yes, indeed.  Already implemented.  A little cumbersome if there are many nodes, and I also found that I inadvertently moved two nodes when shift-clicking, but I understand there needs to be some selection mechanism, so this is servicable.  Thanks.
