### ISSUE TITLE
NISAR GUNW phase display does not allow full adjustment of color scale

### ISSUE THREAD

**Issue by EJFielding** [aivazis/qed#55]
Displaying the phase layer of NISAR GUNW files only allows phase between 0 and 2 pi or 0 and 4 pi radians to be selected in the color scale adjustment. This makes it not usable for most GUNW files.

**Comment by EJFielding** [comment]
Here is a screenshot from QED displaying an ISCE2 UNW file that has the same problem. The display settings tool only allows the unwrapped phase color scale to go from 0 to 2-pi. It seems that all but a tiny area of this particular interferogram is outside that range and shown as "no data".
![ISCE2_ALOS2_phase](https://github.com/aivazis/qed/assets/7253576/eb3f1274-06e0-4b17-8727-c7cb223deddf)

**Comment by aivazis** [comment]
@EJFielding, things should be better now, after 208011200ac4a7d25a3c52f848746fd780245b38. do you mind giving it a try?

the initial range limits are still a bit too wide for many of the images i've tried, making the selection of a sensible value range a bit too twitchy for my taste. i have some ideas about how to fix that, so that's next.

Also, let's find some time for me to show you how you can simplify the process of installing updates on the on-demand system so staying current with progress is not painful. Also, i can show you how to mount your scratch area as a persistent archive, which will help with doing the same for your favorite s3 buckets

**Comment by aivazis** [comment]
Here is a screenshot for the GUNW in the NISAR product samples web site:

<img width="1518" alt="gunw" src="https://github.com/aivazis/qed/assets/6324937/1d0871e7-93b9-4ff8-97b4-c4d9b7d3a13d">

**Comment by parosen** [comment]
Eric, you should respond to Michael if this is working for you.  He prioritized fixing it, and would appreciate rapid feedback.

**Comment by EJFielding** [comment]
Sorry, I missed the post on GitHub

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Paul Rosen ***@***.***>
Sent: Friday, March 15, 2024 4:23:33 PM
To: aivazis/qed ***@***.***>
Cc: Fielding, Eric J (US 329A) ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [aivazis/qed] NISAR GUNW phase display does not allow full adjustment of color scale (Issue #55)


Eric, you should respond to Michael if this is working for you. He prioritized fixing it, and would appreciate rapid feedback.

**Comment by EJFielding** [comment]
Thanks to some additional help from Michael with an extra fix and debugging, I got a reasonable display of an unwrapped interferogram from the 2024 Japan earthquake. This has a larger range of phase values from -13 to +24 radians, so it was important to adjust the color scale.
<img width="1393" alt="ISCE2-unw-display" src="https://github.com/aivazis/qed/assets/7253576/e404bdea-20a9-4a98-92f3-5fc084f95b41">

This is from an ISCE2 alos2App processing, so the "no data" where there was no good unwrapped phase is set to zero radians.

**Comment by EJFielding** [comment]
I would like to make another related request to allow us to set the zero unwrapped phase to black or white, since it is "no data". Should I open another issue?

**Comment by aivazis** [comment]
yes, please. something to the effect to allow a "no-data" value to have a configurable color. i was going to use transparent, which let's the background color through, but maybe you prefer something different
